### ISSUE TITLE
Breaking interaction with "HTML CSS Support" by ecmel

### ISSUE THREAD

**Issue by Jonas-Seiler-Wave** [ghaschel/vscode-angular-html#46]
The extension by itself is great, but unfortunately it seems to break <a href="https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css">HTML CSS Support</a>, so it's not usable for me.
The issue is that once this extension is enabled, the automatic class name completion from the other extension ceases to work completely.
This is also the case outside of angular projects and even occurs when only these two extensions are enabled.

**Comment by ghaschel** [comment]
I think I might have found a fix for this. Gonna try some things here.

**Comment by ghaschel** [comment]
I pushed some changes that might fix this. Can you please check if version 1.8.2 fixed this, please?

**Comment by Jonas-Seiler-Wave** [comment]
Sorry, it still doesn't seem to work... Can you replicate the bug? Is there some info I can provide that would help with debugging?

**Comment by ghaschel** [comment]
Well, if you could provide me a tiny repo in which this error is occurring, alongside with your list of installed extensions.

You can get this list on your terminal of choice by running `code --list-extensions`

**Comment by Jonas-Seiler-Wave** [comment]
I've set up a minimal repo to showcase the issue:
https://github.com/Jonas-Seiler-Wave/vscode-angular-html-Bug-Reproduction

The behavior I am experiencing is that if I enable vscode-angular-html the CSS intellisense from HTML CSS Support ceases to work in .html files.

**Comment by ghaschel** [comment]
Thank you. I'm looking into it right now

**Comment by ghaschel** [comment]
Ok, with your repo I was able to reproduce it.
The extension actually works, if you manually trigger the "Trigger Event" command. I'm using it as `ctrl+space`. It only doesn't trigger it automatically on type.

![image](https://user-images.githubusercontent.com/5878866/184175188-9af047ea-8a68-40c6-8130-b6dc2589cdc3.png)

The same issue is happening to [vscode-html-scss](https://github.com/P-de-Jong/vscode-html-scss/). I was able to reproduce it as well.

Now I'll be able to try to come up with a fix.

**Comment by ghaschel** [comment]
Though this seems like it **might** [be an issue with these extensions](https://github.com/ecmel/vscode-html-css/issues/126), as it is working just fine using [Path Intelisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)

![2022-08-11 12-54-52 (online-video-cutter com)](https://user-images.githubusercontent.com/5878866/184183950-adace8b0-aa4d-443a-bfa8-43f103e83501.gif)

**Comment by ghaschel** [comment]
Fixed. Please confirm it is working on 1.8.4

**Comment by Jonas-Seiler-Wave** [comment]
Yup, can confirm it works. Thanks!

**Comment by NeuSandeZ** [comment]
As of today i happen to have the same bug that this extension breaks HTML CSS Support extension.

**Comment by ghaschel** [comment]
@NeuSandeZ can you please provide me a list of installed extensions so that I can take a look at what might be conflicting?

`code --list-extensions`

**Comment by NeuSandeZ** [comment]
@ghaschel Hey there! Sure thing! Here they are!

angular.ng-template
ecmel.vscode-html-css
ghaschel.vscode-angular-html
ms-dotnettools.csdevkit
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-dotnettools.vscodeintellicode-csharp
patcx.vscode-nuget-gallery
pkief.material-icon-theme
zignd.html-css-class-completion

**Comment by NeuSandeZ** [comment]
@ghaschel Hey sorry about that i've just noticed that it list most of my extansions as anuglar.ng-template hence i decided to provide you with screenshots of them!

![1](https://github.com/ghaschel/vscode-angular-html/assets/44132675/cf793b60-e698-46e0-8311-11021466ab57)
![23214214](https://github.com/ghaschel/vscode-angular-html/assets/44132675/13d145c6-6d09-4f82-aadb-9d89d3caa6c5)

angular.ng-template
ecmel.vscode-html-css
ghaschel.vscode-angular-html
ms-dotnettools.csdevkit
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-dotnettools.vscodeintellicode-csharp
patcx.vscode-nuget-gallery
pkief.material-icon-theme

**Comment by ghaschel** [comment]
@NeuSandeZ I opened a new issue for us to troubleshoot it

https://github.com/ghaschel/vscode-angular-html/issues/94
